services:
  next-app:
    container_name: winwaterfall
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - "11315:3000"
    volumes:
      - ./uploads:/app/uploads:rw,noexec,nosuid,nodev

    read_only: true
    tmpfs:
      - /tmp:uid=1001,gid=1001,mode=1777
      - /app/.next/cache:uid=1001,gid=1001,mode=1777
    
    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true
      
    extra_hosts:
      - "host.docker.internal:host-gateway"


